version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/8466
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 30000
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30000
      runas: root
