version: 0.0
os: linux
files:
  - source: /DSCC_CW1_API_8466/DSCC_CW1_API_8466/bin/Release/net5.0/publish/
    destination: /var/www/html
hooks:
  ApplicationStart:
    - location: start_application.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_application.sh
      timeout: 300
      runas: root
